version: '3.8'

services:
  php-app:
    build: .
    container_name: tienda_Miyagi-Do
    ports:
      - "8080:80"
    env_file: .env  
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres-db  
    environment:
    # Variables que la aplicación PHP puede usar para conectar con la base de datos
      DATABASE_HOST: ${POSTGRES_HOST}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_PORT: ${POSTGRES_PORT}
      # Define la raíz de documentos para Apache dentro del contenedor
      APACHE_DOCUMENT_ROOT: /var/www/html/src
    networks:
      - tienda-network
    

  postgres-db:
    image: postgres:12-alpine
    container_name: postgres-db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    environment:
     # Variables para crear la base de datos y el usuario
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  
    networks:
      - tienda-network  
  adminer:
    # Servicio Adminer para administrar la base de datos vía web
    image: adminer
    container_name: adminer-MiyagiDo
    env_file: .env
    ports:
      - "8081:8080"
    depends_on:
      - postgres-db
    networks:
      - tienda-network
# Volúmenes para persistir datos de PostgreSQL      
volumes:
  db_data:      
# Red personalizada para que los contenedores se comuniquen fácilmente
networks:
  tienda-network:
    driver: bridge
